import { test, expect } from '@playwright/test'
const candidate = {item_id:'12345',title:'SHARP LJ64HB34 工业拆机 TFEL 屏',listed_price:180,rule_interest_score:92,price_confidence:90,price_type:'NEGOTIABLE_REAL_PRICE',detected_models:[{model:'LJ64HB34'}],risk_flags:['UNTESTED'],evaluation_reason:'罕见显示技术，值得点开核实，不代表值得购买。',image_urls:['https://example.com/image.jpg'],url:'https://www.goofish.com/item?id=12345',evaluated_at:'2026-10-04'}
for (const width of [360, 390, 450]) {
 test(`candidate layout and details at ${width}px`, async ({page}) => {
  await page.setViewportSize({width,height:800})
  await page.addInitScript(() => {localStorage.setItem('radar_backend','http://192.168.1.20:8000');localStorage.setItem('auth_logged_in','true')})
  await page.route('**/health', r=>r.fulfill({json:{status:'healthy'}}))
  await page.route('**/api/radar/summary', r=>r.fulfill({json:{items_today:5,candidates:1}}))
  await page.route('**/api/radar/candidates**', r=>r.fulfill({json:{total:1,items:[candidate]}}))
  await page.goto('/#/candidates')
  await expect(page.getByText('● ONLINE')).toBeVisible()
  await expect(page.getByRole('heading',{name:candidate.title})).toBeVisible()
  await expect(page.getByText('Interest 92/100 · Price confidence 90/100')).toBeVisible()
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy()
  await page.getByText('VIEW DETAILS').click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.getByRole('button',{name:'CLOSE',exact:true}).click()
  const popup=page.waitForEvent('popup')
  await page.getByRole('button',{name:'OPEN IN XIANYU',exact:true}).click()
  expect((await popup).url()).toContain('goofish.com/item?id=12345')
 })
}
test('backend address persists, offline remains usable, validation rejects credentials',async({page})=>{
 await page.goto('/#/backend')
 await page.getByLabel('Backend URL').fill('http://user:secret@192.168.1.20:8000')
 await page.getByRole('button',{name:'CONNECT',exact:true}).click()
 await expect(page.getByRole('alert')).toContainText('without credentials')
 await page.route('**/health',r=>r.abort())
 await page.getByLabel('Backend URL').fill('http://192.168.1.20:8000/')
 await page.getByRole('button',{name:'CONNECT',exact:true}).click()
 await expect(page.getByRole('alert')).toBeVisible()
 await page.reload()
 await expect(page.getByLabel('Backend URL')).toHaveValue('http://192.168.1.20:8000')
 await page.goto('/#/dashboard')
 await expect(page.getByText('● OFFLINE')).toBeVisible()
 await expect(page.getByRole('link',{name:'SETTINGS',exact:true})).toBeVisible()
})
test('connect probes configured API origin and uses existing backend login',async({page})=>{
 await page.route('http://192.168.1.20:8000/health',r=>r.fulfill({json:{status:'healthy'}}))
 await page.goto('/#/backend')
 await page.getByLabel('Backend URL').fill('http://192.168.1.20:8000')
 await page.getByRole('button',{name:'CONNECT',exact:true}).click()
 await expect(page).toHaveURL(/#\/login/)
 await expect(page.getByText('● ONLINE')).toBeVisible()
})
